### PR TITLE
Update repositories.txt

### PR DESCRIPTION
**Pull request by lgg42**
Add Piwik Analytics and Coinhive plugin

### CODE REVIEW

**Comment by clickwork-git** [comment]
Why a plugin for a Coinhive miner?!

**Comment by lgg42** [comment]
@clickwork-git just because :-P
I know it's kinda controversial, but I made it for people that want to implement it, even if it's just for testing purposes (high traffic site) or for plain profiting. I don't know if there's a Bludit plugin for Ads, so this could be also a way for profiting a site. Also there are people that don't like Ads but want to get some money from their content. This is a way.

I didn't want it to be so aggressive that's why it's disabled for mobile devices. In future releases I'll add more options to implement opt-in. Meanwhile it just makes possible to append the mining script without modifying the theme's index.php.

**Comment by clickwork-git** [comment]
Okay, I have learned that also a well known CMS has Coinhive plugins. ;-)

**Comment by lgg42** [comment]
I just learned it too :-) thanks!

**Comment by clickwork-git** [comment]
Several things...

1. Your plugins are for Bludit 1.6.2, the latest version is Bludit 2.0.2.
2. Piwik: Why placing the code in the header? Depending on the installation Piwik can slow down a website. Therefore the script normally is placed in the footer. Or is there any reason for this?
3. It makes no sense to add language files for languages that are not translated.

**Comment by lgg42** [comment]
Sh*t!! And I though I was using version 2!! Sorry, my bad! Thanks  for pointing out pointing out moving the Piwik code to the Body end. My bad also about the languages.

**Comment by dignajar** [comment]
Hi, the PR is in conflict, feel free to open a new one with the changes.

**Pull request closed without merging**
